name: Node.jsCI

on:
  push:
    branches: [$default-branch]
  pull_request:
    branches: [$default-branch]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-versions: [10.x, 12.x, 14.x 15.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{matrix.node-versions}}
        uses: actions/setup-node@v1
        with:
          node-version: $${{matrix.node-version}}
      - run: npm install -g bats
      - run : bats -v
